### ISSUE TITLE
Custom config folder with --configdir doesn't include save folder

### ISSUE THREAD

**Issue by iantpryor** [mupen64plus/mupen64plus-ui-console#23]
When using the `--configdir` option with mupen64plus-ui-console, only the config file is read in.  The save folder (which is in the original config folder) is doesn't use the new custom path.

**Comment by richard42** [comment]
Are you saying that if you specify an override directory with the --configdir option, it uses its default directory (ie, ~/.config/mupen64plus for linux/osx) to save the updated config file?

Or are you saying that the directory containing savestate/eprom files is not altered with the --configdir option?

**Comment by iantpryor** [comment]
On windows, the config directory is /AppData/Roaming/Mupen64Plus.  The save and screenshot directories are also in this folder.  I thought using the --configdir option would include everything else in the config directory as well.

I wanted to change where the native saves were being stored, but I don't see a way to do that currently.

**Comment by richard42** [comment]
I looked through the code for this, and it's pretty complicated.  The --configdir option only changes the place where the core will look to find the config file (mupen64plus.cfg).  Fortunately, there is an option ("SaveStatePath" in the [Core] section) in the config file which you can use to specify the savestate location.
