### ISSUE TITLE
[SOLVED] Bad value during make

### ISSUE THREAD

**Issue by knuxyl** [mupen64plus/mupen64plus-ui-console#34]
Debian Stretch 9.0 (1.9) ASUS Tinkerboard RK3288 ARMv7 Mali T764

make NEON=1 VFP_HARD=1 all
```
    CC  _obj/cheat.o
    CC  _obj/compare_core.o
    CC  _obj/core_interface.o
    CC  _obj/main.o
    CC  _obj/plugin.o
    CC  _obj/osal_dynamiclib_unix.o
    CC  _obj/osal_files_unix.o
    LD  mupen64plus
/usr/bin/ld: /tmp/ccSs1UeW.ltrans0.ltrans.o: relocation R_ARM_THM_MOVW_ABS_NC against `a local symbol' can not be used when making a shared object; recompile with -fPIC
/tmp/ccSs1UeW.ltrans0.ltrans.o: error adding symbols: Bad value
collect2: error: ld returned 1 exit status
Makefile:315: recipe for target 'mupen64plus' failed
make: *** [mupen64plus] Error 1
    LD  mupen64plus
/usr/bin/ld: /tmp/ccBHpyWe.ltrans0.ltrans.o: relocation R_ARM_THM_MOVW_ABS_NC against `a local symbol' can not be used when making a shared object; recompile with -fPIC
/tmp/ccBHpyWe.ltrans0.ltrans.o: error adding symbols: Bad value
collect2: error: ld returned 1 exit status
Makefile:315: recipe for target 'mupen64plus' failed
make: *** [mupen64plus] Error 1
```
-fPIC seems to be required during compilation of ld.

I tried with setting the PIC option during make
```
make NEON=1 VFP_HARD=1 PIC=1 all
make NEON=1 VFP_HARD=1 PIC=0 all
```
but still the same error

Finding the line in projects/unix/Makefile
```
ifeq ($(OS), LINUX)
  LDLIBS += -ldl
endif
```
and adding
```
ifeq ($(OS), LINUX)
  LDLIBS += -ldl
  CFLAGS += -fPIC   #THIS LINE
endif
```
used to fix the problem, it's not working now

Adding PIE=1 to make fixed the problem. thanks loganmc10.

**Comment by loganmc10** [comment]
I believe you need to set PIE=1, not PIC=1

**Comment by Enverex** [comment]
Is it worth adding the PIE=1 bit to the main documentation? It doesn't build on Arch Linux without adding this which confused me for a good few hours (considering that it complains about PIC and not PIE).

**Comment by loganmc10** [comment]
Yeah I noticed it's required in the latest Ubuntu as well, it might be worth it to make it the default

**Comment by richard42** [comment]
Are people seeing the build errors with x86/amd64 machines as well, or is this only on ARM cpus?

**Comment by loganmc10** [comment]
I had this on Ubuntu x64

**Comment by richard42** [comment]
This kind of sucks. The PIE option is used for hardening executables against certain types of vulnerabilities. I don't think it's really necessary for mupen64plus. I don't know why the distro or compiler would change default options to make this required for all executables; it seems like this would cause a lot of grief. It would be a good idea to add something to the README file or other documentation to warn people about this, but I would not want to make the PIE=1 option the default yet.

**Comment by loganmc10** [comment]
Yeah it seems like Ubuntu did it starting in 16.10:

https://lists.ubuntu.com/archives/snapcraft/2017-February/003339.html

I'm not sure why it seems to be forced, but I definitely ran into this issue in x64 Ubuntu

**Comment by loganmc10** [comment]
Also:

https://wiki.ubuntu.com/SecurityTeam/PIE

**Comment by loganmc10** [comment]
Sorry for the triple post maybe https://github.com/mupen64plus/mupen64plus-ui-console/blob/master/projects/unix/Makefile#L87 just needs to be changed to ```no-pie``` is it case sensitive?

**Comment by richard42** [comment]
it looks to me like GCC is supposed to support both -no-pie and -no-PIE. Can somebody with ubuntu 16.10 test, to see if changing the case resolves this?

**Comment by loganmc10** [comment]
I tried on Ubuntu 17.04, I had to add -no-pie to the linker flags. It worked and I submitted a PR: https://github.com/mupen64plus/mupen64plus-ui-console/pull/36

But then Travis failed. I guess -no-pie is only available on later GCC versions?

**Comment by richard42** [comment]
I have GCC 5.4.0, and it does accept the "--no-pie" option, but not "-no-pie"
