### ISSUE TITLE
Fails to build under windows

### ISSUE THREAD

**Issue by charlemagnelasse** [mupen64plus/mupen64plus-ui-console#39]
It fails to build under windows with:

    x86_64-w64-mingw32.static-gcc: error: unrecognized command line option '-no-pie'

Please revert https://github.com/mupen64plus/mupen64plus-ui-console/commit/187d3a3bda7044a78babd4328428b2cff7e89a02

**Comment by charlemagnelasse** [comment]
@loganmc10  The problem here is the call to gcc in PIE_DEFAULT. This is not the linker which is used by the Makefile. The actual compiler would be $(CC)

**Comment by loganmc10** [comment]
If you change ```gcc``` to ```$(CROSS_COMPILE)gcc``` does it fix it? Are you actually compiling on Windows or are you cross compiling from Linux?

**Comment by loganmc10** [comment]
Or change ```gcc``` to ```$(CC)```

**Comment by charlemagnelasse** [comment]
No, $(CROSS_COMPILE)gcc is wrong. As said earlier, it has to be $(CC) because CC is overwritten using env with x86_64-w64-mingw32.static-gcc

**Comment by loganmc10** [comment]
So changing it to $(CC) works?

**Comment by loganmc10** [comment]
If $(CC) works then $(CROSS_COMPILE)GCC must work, this whole thing is inside:

```ifeq ($(CC),$(CROSS_COMPILE)gcc)```

So they must be the same
