### ISSUE TITLE
Missing definitions of m64p_media_loader and M64CMD_SET_MEDIA_LOADER

### ISSUE THREAD

**Issue by jkbenaim** [mupen64plus/mupen64plus-ui-console#46]
Commit 5b9eba4cabbbdcee668b37fa263b50c614b8be69 (as I write, current master) is missing definitions for `m64p_media_loader` and `M64CMD_SET_MEDIA_LOADER`, resulting in build errors.

```
    CC  _obj/main.o
../../src/main.c:830:8: error: unknown type name ‘m64p_media_loader’
 static m64p_media_loader l_media_loader =
        ^~~~~~~~~~~~~~~~~
../../src/main.c: In function ‘main’:
../../src/main.c:1028:26: error: ‘M64CMD_SET_MEDIA_LOADER’ undeclared (first use in this function)
     if ((*CoreDoCommand)(M64CMD_SET_MEDIA_LOADER, sizeof(l_media_loader), &l_media_loader) != M64ERR_SUCCESS)
                          ^~~~~~~~~~~~~~~~~~~~~~~
../../src/main.c:1028:26: note: each undeclared identifier is reported only once for each function it appears in
Makefile:321: recipe for target '_obj/main.o' failed
make: *** [_obj/main.o] Error 1
```

**Comment by bsmiles32** [comment]
These definitions are found in the core. See https://github.com/mupen64plus/mupen64plus-core/blob/12c668408dde27c995a0433ea7aebaed55fddf68/src/api/m64p_types.h#L201

Using the latest version of the core will give you access to these missing definitions.

**Comment by jkbenaim** [comment]
@bsmiles32 You're right, and I feel like an idiot. Thanks for the help! 👍
