### ISSUE TITLE
2.5.9: Missing config API change

### ISSUE THREAD

**Issue by charlemagnelasse** [mupen64plus/mupen64plus-ui-console#54]
The ui is currently depending on config api 2.0

    src/version.h:#define CONFIG_API_VERSION 0x020000

The ui-console program is using following new functions from newer API versions:

* 2.1
  -  ConfigSaveSection
* 2.2
  - ConfigHasUnsavedChanges
* 2.3.1
  - ConfigExternalOpen

**Comment by richard42** [comment]
okay, this should be fixed now.
