### ISSUE TITLE
Build error after #61 merged

### ISSUE THREAD

**Issue by tokumeiwokiboushimasu** [mupen64plus/mupen64plus-ui-console#62]
#61  seems to cause a building error on ubuntu 20.04.

>    /usr/bin/ld: /tmp/mupen64plus.7qvaaK.ltrans0.ltrans.o: relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a PIE object; recompile with -fPIE collect2: error: ld returned 1 exit status

If I revert this commit, the error has gone.

**Comment by Narann** [comment]
It could be interesting to update travis config so it tests with multiples Ubuntu versions.

**Comment by joolswills** [comment]
The commit is wrong. I added some comments to the PR linked above.

**Comment by Jj0YzL5nvJ** [comment]
What's happens if you replace `$(CROSS_COMPILE)` with `${CROSS_COMPILE}`?
