### ISSUE TITLE
How to view osSyncPrints?

### ISSUE THREAD

**Issue by dustinlacewell** [mupen64plus/mupen64plus-ui-console#73]
I'm doing some Ocarina of Time development and Mupen is the only emulator I can get on NixOS.

How can I view the various calls to `osSyncPrint` in the game, and the ones I've added?

Thanks.

**Comment by richard42** [comment]
what is osSyncPrint? Normally the debug function calls write their messages out to STDOUT or STDERR

**Comment by dustinlacewell** [comment]
@richard42 I guess it is the name of the function inside Ocarina of Time used for doing IS64 debug logging. The latest development versions of mupen now report this to the UI console when in debug mode so this can be closed.
