### ISSUE TITLE
Unrecognized UI-Console commands

### ISSUE THREAD

**Issue by Scallonni** [mupen64plus/mupen64plus-ui-console#76]
Hello everyone! I have noticed that some string arguments of the --set parameter are not working properly. The pre-release 2.5.9 build works fine, but not the latest nightly-builds.
I'll explain better... I use several mupen64plus.cfg (to be exact, one for each game), and I try to keep them in the same directory as the emulator. That way I can make each game run with a unique configuration for it.

Going to my Mupen directory "C:\mupen64plus" through the Prompt, I run, for example, San Francisco Rush 2049:

`mupen64plus-ui-console.exe --configdir "romconfig\San Francisco Rush 2049 (U) [!]" "roms\San Francisco Rush 2049 (U) [!].z64"`

It's all right...
1st: My mupen64plus.cfg will be created in the folder "C:\mupen64plus\romconfig\San Francisco Rush 2049 (U) [!]", and no longer in default "C:\Users\ (User) \AppData\Roaming\Mupen64Plus".
2nd: I close the game
3rd: I change my new mupen64plus.cfg as I want
4th: I run exactly the same command mentioned above so that the emulator continues reading my new mupen64plus.cfg when I want to play again.

The problem I reported happens when I want to quickly configure some parameters of my new mupen64plus.cfg using the prompt. I could do this by editing my new mupen64plus.cfg with a text editor (as I've explained), but I can speed things up like this.
For example: to define a new path for my screenshots, I would do:

`mupen64plus-ui-console.exe --configdir "romconfig\San Francisco Rush 2049 (U) [!]" --set core[ScreenshotPath]="romconfig\San Francisco Rush 2049 (U) [!]\screenshot" "roms\San Francisco Rush 2049 (U) [!].z64"`

As a result, in my mupen64plus.cfg:
[Core]
(...)
ScreenshotPath = "romconfig\San Francisco Rush 2049 (U) [!]\screenshot"
(...)

But this is what I get now :(
ScreenshotPath = ""romconfig\San" (It's three quotes, I wasn't wrong)

And I still get a pile of unrecognized commands that I get later:
UI-Console Warning: unrecognized command-line parameter 'Francisco'
UI-Console Warning: unrecognized command-line parameter 'Rush'
UI-Console Warning: unrecognized command-line parameter '2049'
UI-Console Warning: unrecognized command-line parameter '(U)'
Etc.....

I'll avoid theories here so this text doesn't get too long.
Goodbye!

**Comment by Narann** [comment]
Looks like you find an interesting parsing error.

**Comment by richard42** [comment]
I looked over the code in the ui-console project which parses these --set options, and I think you are running into a problem with the Windows terminal and the command-line parameter escaping behavior. The entire param-spec (which in your case is `core[ScreenshotPath]="romconfig\San Francisco Rush 2049 (U) [!]\screenshot"`) needs to be seen as a single command-line argument by the mupen64plus-ui-console.exe application, but I don't think that's happening. I would try putting the quotation mark at the beginning of the argument rather than in the middle, like this:
`--set "core[ScreenshotPath]=romconfig\San Francisco Rush 2049 (U) [!]\screenshot"`
Maybe the Windows terminal will handle it correctly like that.

**Comment by Scallonni** [comment]
It worked! It was very strange for me that the command-line parameter escape behaved differently in old builds, so I figured a possible regression. I hope you understand me! good job everyone

**Comment by richard42** [comment]
yeah I don't understand either, how it could have worked in older builds but failed with the current source code. I think this problem is not even due to anything in Mupen64plus, but a behavior of the shell.  But I'm glad you got it to work for you!

**Comment by Jj0YzL5nvJ** [comment]
In case you are interested in seeing what a nested syntax for a bash script looks like, a good example can be seen in second 2 of [this video](https://imgur.com/6XXHQnc).

For mpv users: `mpv --fs --start=+2 --pause https://i.imgur.com/6XXHQnc.mp4`

The script:
```
#!/bin/bash
set -e

ORIG=`dirname "${0}"`
if [[ -z ${CORE_NAME} ]]; then CORE_NAME="libmupen64plus.so.2.0.0"; fi
#mkdir -p "${ORIG}/screenshot" "${ORIG}/save" "${ORIG}/hires_texture"
#PORTABLE="--corelib ${ORIG}/${CORE_NAME} --plugindir ${ORIG} --datadir ${ORIG} --configdir ${ORIG} --sshotdir ${ORIG}/screenshot --set Core[SaveStatePath]=${ORIG}/save --set Core[SaveSRAMPath]=${ORIG}/save"
SEMIPORTABLE="--corelib ${ORIG}/${CORE_NAME} --plugindir ${ORIG} --datadir ${ORIG}"

# Utilities
#export LIBGL_SHOW_FPS="1"
#export GALLIUM_HUD="cpu+GPU-load+fps"

# Troubleshooting
#export LIBGL_ALWAYS_SOFTWARE="1"
#export MESA_GLSL_CACHE_DISABLE="1"
#export MESA_GL_VERSION_OVERRIDE="3.3COMPAT" MESA_GLSL_VERSION_OVERRIDE="330" MESA_EXTENSION_OVERRIDE="-GL_ARB_buffer_storage"

#${ORIG}/./mupen64plus ${PORTABLE} --set Video-GLideN64[txPath]=${ORIG}/hires_texture "${@}"
${ORIG}/./mupen64plus ${SEMIPORTABLE} "${@}"

```

Another example but without script:
```
mupen64plus --corelib ${HOME}/m64p/test/libmupen64plus.so.2.0.0 --plugindir ${HOME}/m64p/test --datadir ${HOME}/m64p/test --configdir /tmp --gfx mupen64plus-video-angrylion-plus.so --rsp mupen64plus-rsp-parallel.so --set Input-SDL-Control1[mode]=0 --set Input-SDL-Control1[mouse]=True --set Input-SDL-Control1[Z\ Trig]="key(122) mouse(1)" --set Input-SDL-Control1[B\ Button]="key(306) mouse(2)" --set Input-SDL-Control1[R\ Trig]="key(99) mouse(3)" --set Video-Angrylion-Plus[Parallel]=True --set Video-Angrylion-Plus[NumWorkers]=4 --set Video-Angrylion-Plus[ViMode]=1 --set Video-Angrylion-Plus[DpCompat]=2 --windowed --resolution 640x480 --emumode 2 "/tmp/Turok 2 - Seeds of Evil (U).z64"
```

**Comment by Scallonni** [comment]
I'm very happy for your clarification! I have preferred to learn about nested syntaxes rather than being restricted to UI Interfaces, so I can learn even more about Mupen. This will help me a lot with my tests. I'm Brazilian and I really admire the work of all of you. My sincere thanks, bye

**Comment by Jj0YzL5nvJ** [comment]
I correct myself, it's _"nested argument"_ not _"nested syntax"_.

A few years ago I had the ambitious idea to create a script with shorter syntax to manipulate mupen64plus. But before long I came to my senses and just wrote the optimal settings in individual scripts... it's simpler and more effective than trying to create a script to parse and translate the syntax to the UI Console.

Example:
```
#!/bin/bash
set -e

if [[ -z ${HLE} ]]; then HLE="1"; fi
if [[ ${HLE} -eq 1 ]]; then
	export PLUGINS="--gfx mupen64plus-video-GLideN64.so --rsp mupen64plus-rsp-cxd4-sse2.so --audio mupen64plus-audio-sdl2.so --set rsp-cxd4[DisplayListToGraphicsPlugin]=True"
	export GFX="--set Video-GLideN64[ThreadedVideo]=True -set Video-GLideN64[UseNativeResolutionFactor]=4 --set Video-GLideN64[EnableDitheringPattern]=True --set Video-GLideN64[EnableHiresNoiseDithering]=True --set Video-GLideN64[DitheringQuantization]=True --set Video-GLideN64[RDRAMImageDitheringMode]=3 --set Video-GLideN64[EnableTexCoordBounds]=1 --set Video-GLideN64[EnableN64DepthCompare]=2 --set Video-GLideN64[EnableCopyColorToRDRAM]=1"
else
	export PLUGINS="--gfx mupen64plus-video-angrylion-plus.so --rsp mupen64plus-rsp-parallel.so --audio mupen64plus-audio-sdl2.so"
	export GFX="--set Video-AngrylionPlus[Parallel]=True --set Video-AngrylionPlus[NumWorkers]=4 --set Video-AngrylionPlus[BusyLoop]=True --set Video-AngrylionPlus[DpCompat]=2"
fi

m64pp --windowed --resolution 1280x960 ${PLUGINS} ${GFX} "${@}"

```

This script is supposed to be executed from the PATH environment in the following way:
```
HLE=0 my_example.sh "ROMS/N64/Banjo-Kazooie (U).z64"
```
or
```
my_example.sh ROMS/N64/Banjo-Kazooie\ \(U\)\ \(V1.0\)\ \[\!\].z64
```

P.S: `m64pp` is the first script =P

[Other example.](https://github.com/gonetz/GLideN64/wiki/Build-From-Source-(Linux)#examples-of-use)
